name: 部署 Github Pages

on:
  push:
    branches: [main]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 26

      - uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: true

      - name: 构建
        run: pnpm run docs:build

      - name: 部署
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
          force_orphan: true
